### ISSUE TITLE
Error: _pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by VoHoangAnh** [HowieMa/CVTHead#2]
Thank you for your great work!
I set up the environment as requirements.txt, however, I met this error when the model file "data/cvthead.pt"  was loaded in inference.py  

magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<' 

I am very thankful if you can suggest the solution to fix it.

**Comment by VoHoangAnh** [comment]
I solved it 
Thank you.

**Comment by VoHoangAnh** [comment]
I solved it 
Thank you.

**Comment by LeeTeng2001** [comment]
hey, what's the solution here???

**Comment by VoHoangAnh** [comment]
I saved the model file in another PyTorch version.

**Comment by cvipym** [comment]
Hi, could you please provide more detailed steps on how to save the model file in a different PyTorch version? I'm having trouble understanding the process and would appreciate your guidance.

**Comment by VoHoangAnh** [comment]
In my case, I used torch 1.11.0 instead of torch 2.0, as illustrated in requirement.txt.
you can save the model file in torch 1.11.0 and then use torch 2.0 to load it. I don't know the reason but it worked

**Comment by cvipym** [comment]
Thank you, I appreciate your response.
But, I don't understand saving the model using torch. 
Aren't files downloaded using bash scripts?

**Comment by YacratesWyh** [comment]
Google Drive using bash to download would cause viruse scan instead of direct download it, it's an update version. You have to download it manually.
If you want a quick check, just check your model, whether they are very tiny like 3KB, then the .sh is failed like me.
@HowieMa Hope you fix this

**Comment by YacratesWyh** [comment]
https://github.com/tensorflow/datasets/issues/3935
To solve this, add like this in bash

**Comment by mengsiwei** [comment]
> Hi, could you please provide more detailed steps on how to save the model file in a different PyTorch version? I'm having trouble understanding the process and would appreciate your guidance.

Hello! Have you solved this problem now? I also encountered this problem.
